project:
  type: website
  output-dir: docs

website:
  title: "{{< fa feather >}} Blog de apuntes"
  favicon: "feather.svg"
  navbar:
    background: "#f7f7f7"
    foreground: "#252D5C"
    right:
      - icon: github
        href: https://github.com/Dani2509

format:
  html:
    theme: 
      - Zephyr
      - style.scss
    toc: true

execute: 
  freeze: auto
  warning: false
  message: false


