project:
  type: website
  output-dir: docs

website:
  title: "{{< fa feather >}} Blog de apuntes"
  navbar:
    background: "#f7f7f7"
    foreground: "#252D5C"
    right:
      - icon: github
        href: https://github.com/Dani2509

format:
  html:
    theme: 
      - minty
      - style.scss
    toc: true

editor: visual

