project:
  type: website
  output-dir: docs

website:
  title: "{{< fa feather >}} Blog de apuntes"
  navbar:
    background: "#e9edc9"
    right:
      - icon: github
        href: https://github.com/Dani2509

format:
  html:
    theme: minty
    css: style.scss
    toc: true

editor: visual

