project:
  type: website
  output-dir: docs

website:
  title: "Blog de apuntes"
  navbar:
    right:
      - icon: github
        href: https://github.com/Dani2509

format:
  html:
    theme: minty
    css: styles.css

editor: visual

