---
title: "Descarga de datos del GBIF"
description: "Descargando datos"
author: "Daniela O"
categories: [SIG, R]
date: 2024-09-17
toc-expand: true
---

Descargando datos

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(rgbif)
```


```{r}
# descargando datos

# Instalar y cargar la librería rgbif si no está instalada
if(!require(rgbif)) {
  install.packages("rgbif")
}
library(rgbif)

# Parámetros de búsqueda
taxon_key <- name_backbone(name="Mammalia")$usageKey # Buscar el código del taxón Mammalia
country_code <- "CO" # Código ISO para Colombia
department <- "Magdalena" # Departamento Magdalena

# Realizar la búsqueda de datos
occ_data <- occ_search(
  taxonKey = taxon_key, 
  country = country_code, 
  stateProvince = department, 
  hasCoordinate = TRUE,  # Filtrar solo registros con coordenadas
  limit = 1000 # Límite de registros
)

# Ver los primeros resultados
head(occ_data$data)


```

```{r}
occ<- data.frame(occ_data$data)
# view(occ)

occ_depu<- occ |> select(-c(5,7,8,9,10,11,12,13,14,17,18,19,20,21,22,23,24,25,26,34,35,39,43:147))

glimpse(occ_depu)
```
```{r}
# write.csv2(occ_depu, "obs_mamigeros.csv")
```

```{r}
# datos de herpetos 
if(!require(rgbif)) {
  install.packages("rgbif")
}
library(rgbif)

# Parámetros de búsqueda
taxon_key <- name_backbone(name="Reptilia")$usageKey # Buscar el código del taxón Mammalia
country_code <- "CO" # Código ISO para Colombia
department <- "Magdalena" # Departamento Magdalena

# Realizar la búsqueda de datos
occ_data <- occ_search(
  taxonKey = taxon_key, 
  country = country_code, 
  stateProvince = department, 
  hasCoordinate = TRUE,  # Filtrar solo registros con coordenadas
  limit = 2000 # Límite de registros
)

# Ver los primeros resultados
head(occ_data$data)

```

```{r}
occ_reptilia<- data.frame(occ_data$data)
#view(occ_reptilia)

occ_depu_r<- occ_reptilia |> select(-c(7,8,9,10:13,14,17:24,36:58,60:101))

glimpse(occ_depu_r)

occ_depu_r$class <- as.factor(occ_depu_r$class)

# Ver los niveles de la variable categórica "class"
nombres_categorias <- levels(occ_depu_r$class)
print(nombres_categorias)

occ_r <- occ_depu_r |> filter(class == c("Amphibia", "Mammalia" , "Squamata"))

# view(occ_r)

# write.csv2(occ_r, "obs_reptilia.csv")
```

